# Generated by Django 6.0.4 on 2026-04-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdanalysis',
            name='resources',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jdanalysis',
            name='study_plan',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
