# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeprofile",
            name="qa",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
